### ISSUE TITLE
[BUG] Update API in usuage not working properly

### ISSUE THREAD

**Issue by Matrixk1ng** [UTDallasEPICS/Hope-Restored-Community-Information-Module#28]
**Describe the bug**
The edit page popup to update the resources does not work as the update api in usuage does not update the resource properly using prisma.

**Expected behavior**
const resource = await prisma.resource.update({
      where: { id },
      data: resourceData,
      include: RESOURCE_INCLUDE_ALL,
    });
    
   something about the update function not working check prisma docs

**Screenshots**

**Additional context**

**Comment by tenvoltz** [comment]
You are sending the entire resource data to the backend, which contain false/old info (For example: if you edit the data like languages to another language like from Spanish to Chinese, the data given to back end contain false info where Chinese id should not be 2 but like 4).  You should only send string value of the editted field to the backend, not the object itself since the object contain old value and thus is false. If you want to do it that way, you need to ensure your data is up to date. Thus text field should not be use for field that need connection like language, location, phone number, and email. Those field need to be populated with drop down that contain up-to-date info with an option to "Add new __" that talk to database to add new object.

**Comment by tenvoltz** [comment]
You should match your API body with CreateResourceInput that is in server/usage/Resource/create.ts
